CREATE TABLE "GCG_6303_Cntrl_Plan"  (
 "TERMINAL" CHAR(3),
 "JOB" CHAR(7)
 "SUFFIX" CHAR(3),
 "RESP_ID" CHAR(10),
 "COMP_ID" CHAR(10),
 "SEQ_NO" INTEGER,
 "DIM_VALUE" CHAR(20),
 "TOLERANCE" CHAR(20),
 "MTNAME" CHAR(50),
 "NOTES" CHAR(50),
 "DET_SAMP_SIZE" INTEGER );

CREATE INDEX "GCG_6303_Cntrl_Plan" ON "GCG_6303_Cntrl_Plan" ( "TERMINAL" );